### ISSUE TITLE
Trying to deploy PCF with Windows on AWS - is vsphere required?

### ISSUE THREAD

**Issue by trondhindenes** [pivotal-cf/docs-pcf-windows#2]
According to this: https://docs.pivotal.io/pivotalcf/1-8/windows/build-stemcell.html
It seems that I need a vSphere install in order to build the windows stemcell required to deploy pcf with Windows on AWS. This strikes me as very backward. We use aws to avoid having to run vsphere locally. Do I have to spin up vsphere just to generate the image? Why not use aws snapshots, virtualbox or any other method? #stuck.

**Comment by trondhindenes** [comment]
Im finding a reference to a "PCF Stemcell for windows": `For AWS, navigate to the **Stemcells for PCF (Windows Server)** section of [Pivotal Network](https://network.pivotal.io/products/stemcells-windows-server).` but that link doesn't exist. It's still extremely unclear to me how to go about deploying PCF for windows with the current doc.

**Comment by trondhindenes** [comment]
I'm seeing now that the doc refers to pcf 1.8 - and is likely outdated. However, I can't find any working documentation for PCF with Windows on 1.10.

**Comment by bentarnoff** [comment]
Hey @trondhindenes, our current recommended workflow for deploying Windows VMs on PCF are by using the PCF Runtime for Windows tile, which is currently only available for PCF 1.9: https://docs.pivotal.io/pivotalcf/1-9/windows/index.html. However, that documentation set doesn't yet have a topic for how to build a vSphere stemcell—but it should soon.

@awmartin may be able to provide more information.

**Comment by bentarnoff** [comment]
Hey @trondhindenes did your discussion with A. William Martin from https://github.com/pivotal-cf/docs-ops-guide/issues/28 settle this issue? If so, I can close it.

**Comment by trondhindenes** [comment]
THanks, figured out 1.9 was the ticket. Closing this.
