### ISSUE TITLE
Link to docs.pivotal.io for "building a vsphere stemcell"

### ISSUE THREAD

**Issue by labrown** [pivotal-cf/docs-pcf-windows#6]
The link in step 10. for building the vSphere Windows stemcell goes off to github.  It should go to https://docs.pivotal.io/pivotalcf/1-11/windows/vsphere-stemcell-build.html instead.

**Comment by cf-pub-tools** [comment]
Hi @labrown Can you tell us which page contains the incorrect link? Thanks!

**Comment by labrown** [comment]
https://docs.pivotal.io/pivotalcf/1-11/windows/deploy-windows.html

**Comment by animatedmax** [comment]
Thank you, @labrown We've added a link to [Creating a vSphere Stemcell Manually](https://docs.pivotal.io/pivotalcf/1-11/windows/vsphere-stemcell-build.html), but also kept the link to [Creating a vSphere Stemcell by Hand](https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder/wiki/Creating-a-vSphere-Stemcell-by-Hand) in GitHub for people who want to follow those instructions instead.
