### ISSUE TITLE
Stemcell virtual machine recommendations don't match VM Types

### ISSUE THREAD

**Issue by gradinDotCom** [pivotal-cf/docs-pcf-windows#8]
https://github.com/pivotal-cf/docs-pcf-windows/blob/b6c8174e3cd81f2cf43619cec283579c5c2ce4c4/docs-content/index.html.md.erb#L24

The default recommendations for the Windows Stemcell does not match the available vm types in OpsMan (resource config). The doc lists 4/16/64, but the p-windows-runtime can't match it.

For what it's worth, I'd like to see better consistency within the vm types, but that's a whole 'nutha ball of wax.

**Comment by mlimonczenko** [comment]
Hello @gradinDotCom,
I got clarification from the development teams that the Windows stemcell requirement was the *minimum* requirement rather than strict settings. I've changed the doc to reflect that change.
